ARROW-9415: [C++] Arrow does not compile on Power9
Fix build on Power9

This small change addresses the following build error:
```[ 20%] Building CXX object src/arrow/CMakeFiles/arrow_objlib.dir/array/builder_nested.cc.o
In file included from /ccs/proj/stf006/glaser/rapids/arrow/cpp/src/arrow/array/dict_internal.h:35:0,
                 from /ccs/proj/stf006/glaser/rapids/arrow/cpp/src/arrow/array/builder_dict.cc:22:
/ccs/proj/stf006/glaser/rapids/arrow/cpp/src/arrow/util/hashing.h: In static member function 'static uint32_t arrow::internal::SmallScalarTraits<__vector(4) __bool int>::AsIndex(__vector(4) __bool int)':
/ccs/proj/stf006/glaser/rapids/arrow/cpp/src/arrow/util/hashing.h:495:60: error: cannot convert '__vector(4) int' to 'uint32_t {aka unsigned int}' in return
   static uint32_t AsIndex(bool value) { return value ? 1 : 0; }                                                            ^
```

The problem is caused by `bool` being defined in altivec.h

Closes #7711 from jglaser/fix_ppc_build

Lead-authored-by: Jens Glaser <glaserj@ornl.gov>
Co-authored-by: Wes McKinney <wesm@apache.org>
Signed-off-by: Wes McKinney <wesm@apache.org>